### ISSUE TITLE
Support configuration files

### ISSUE THREAD

**Issue by kasium** [Bachmann1234/diff_cover#233]
### Current state
All options are given over the CLI which works fine for the most use cases

### My suggestion
In some use cases it's better to use configuration files to define options. In addition, these options can be overwritten with options given to the CLI.

### Implementation
Personally, I would first create a configuration file reader (abstract so it can handle other files in the future). Then I would add a TOML parser (pyproject.toml), because this seems to be the go-to way.

Example toml
```toml
[tool.diff_cover]
compare_branch = "origin/foo"
fail_under = 42

[tool.diff_quality]
fail_under = 23
include = [
  "project/foo/**"
]
```
So, the toml file:

- uses both tools with their name
- same options as on CLI, but with underscores
- if an option can be specified multiple times, the value is a list

### Flow

1. Check if the user specifies a configuration file over CLI; if yes, use that (`--config myfile.toml`)
2. If no, then check if a pyproject.toml exists and check if it contains any section which belongs to us **(do we want to have a magic file name?)**
3. Afterwards merge all configuration values with the given CLI parameters (CLI overwrite config)
4. Proceed as normal
